name: 'Annotated unit tests'
description: 'Runs unit tests and annotates failures'

inputs:
  test-type:
    description: 'The tool used to run tests'
    required: true
  test-script:
    description: 'Npm script used to run the unit tests. (default to test)'
    required: false
    default: 'test'
  token:
    description: 'Github token'
    required: true

runs:
  using: 'node12'
  main: 'src/main.js'