name: lint
on: pull_request

jobs:
  lint:
    runs-on: [self-hosted, Linux, AWS]
    steps:
      - name: Checkout Code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Run lint
        run: npm run lint