name: Test
on: pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: Brightspace/third-party-actions@actions/checkout
      - name: Setup Node
        uses: Brightspace/setup-node@main
        with:
            node-version: '14.x'
            d2l-registry-token: ${{ secrets.D2L_PACKAGE_REGISTRY_AUTH_TOKEN }}
      - name: Install Node Modules
        run: npm ci
      - name: Run lint
        run: npm run lint
      - name: Run test
        uses: ./
        with:
          test-type: mocha
          token: ${{ secrets.GITHUB_TOKEN }}